centos_php54_default:
  image: pozitim-ci/centos-php54
  environment:
    APPLICATION_ENV: pozitim-ci
    NGINX_PUBLIC_FOLDER: /project/public
    NGINX_INDEX_FILE: index.php
  command: sh /init.sh
  ports:
    - 80
  links:
    - centos_php54_mysql
    - centos_php54_memcached
  volumes:
    - ./init.sh:/init.sh
    - ./source-code:/project

centos_php54_mysql:
  image: mysql
  ports:
    - 3306
  environment:
    MYSQL_DATABASE: "database"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

centos_php54_memcached:
  image: memcached
  ports:
    - 11211