web:
  image: pozitim-ci/centos-php55
  environment:
    APPLICATION_ENV: pozitim-ci
    NGINX_PUBLIC_FOLDER: /project/public
    NGINX_INDEX_FILE: index.php
  command: sh /init.sh
  ports:
    - "80:80"
  links:
    - mysql:mysql
    - memcached:memcached
  volumes:
    - ./init.sh:/init.sh
    - ./source-code:/project

mysql:
  image: mysql
  environment:
    MYSQL_DATABASE: "database"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

memcached:
  image: memcached